<a href="https://colab.research.google.com/github/EVRJSASTRY/NASSCOM-AI/blob/main/DAY_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

np.random.seed(42)
print('Setup complete. NumPy', np.__version__)

Setup complete. NumPy 2.0.2

In [ ]:
# P(A) = favourable outcomes / total outcomes.
# We can estimate it by simulating many trials.
rolls = np.random.randint(1, 7, size=100_000)   # 100k dice rolls

p_even = (rolls % 2 == 0).mean()       # P(even)
p_gt4  = (rolls > 4).mean()            # P(roll > 4)
print('P(even) ~', round(p_even, 3), ' (true 0.5)')
print('P(>4)   ~', round(p_gt4, 3),  ' (true 0.333)')

P(even) ~ 0.502  (true 0.5)
P(>4)   ~ 0.334  (true 0.333)

In [ ]:
p_1 = (rolls == 1).mean()
p_2 = (rolls == 2).mean()
p_1_or_2 = (np.isin(rolls, [1, 2])).mean()
print('P(1) + P(2) =', round(p_1 + p_2, 3))
print('P(1 or 2)   =', round(p_1_or_2, 3), ' -> they match')

P(1) + P(2) = 0.334
P(1 or 2)   = 0.334  -> they match

In [ ]:
import numpy as np

# Simulate 100,000 pairs of coin flips
flips = np.random.randint(0, 2, size=(100_000, 2))
heads = flips.sum(axis=1)   # number of heads in each pair

# 1. P(both heads)
p_both_heads = (heads == 2).mean()
print("P(both heads) =", round(p_both_heads, 3))

# 2. P(at least one head)
p_at_least_one = (heads >= 1).mean()
print("P(at least one head) =", round(p_at_least_one, 3))

# 3. Check P(0) + P(1) + P(2)
p0 = (heads == 0).mean()
p1 = (heads == 1).mean()
p2 = (heads == 2).mean()

print("P(0 heads) =", round(p0, 3))
print("P(1 head)  =", round(p1, 3))
print("P(2 heads) =", round(p2, 3))
print("Sum =", round(p0 + p1 + p2, 3))

P(both heads) = 0.252
P(at least one head) = 0.749
P(0 heads) = 0.251
P(1 head)  = 0.497
P(2 heads) = 0.252
Sum = 1.0

In [ ]:
rolls = np.random.randint(1, 7, size=100_000)

# P(roll is 6 | roll is even):  narrow the world to even rolls
even = rolls[rolls % 2 == 0]          # condition on 'even'
p_6_given_even = (even == 6).mean()
print('P(6 | even) ~', round(p_6_given_even, 3), ' (true 1/3)')

P(6 | even) ~ 0.332  (true 1/3)

In [ ]:
A = rolls > 3
B = rolls % 2 == 0
p_A        = A.mean()
p_A_given_B = A[B].mean()
print('P(A)      =', round(p_A, 3))
print('P(A | B)  =', round(p_A_given_B, 3))
print('Independent?', np.isclose(p_A, p_A_given_B, atol=0.02))

P(A)      = 0.498
P(A | B)  = 0.666
Independent? False

In [ ]:
{"username":"sastryevsit","key":"492a7eda8663704ce9a182058ac4eac9"}

{'username': 'sastryevsit', 'key': '492a7eda8663704ce9a182058ac4eac9'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [ ]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
print('Setup complete. pandas', pd.__version__)

Setup complete. pandas 2.2.2

In [ ]:
raw = pd.DataFrame({
    'id':    [1, 2, 3, 4, 5, 6, 7, 7],
    'name':  ['Ana', 'Bo', 'Cy', 'Di', 'Eve', 'Fin', 'Gus', 'Gus'],
    'age':   [30, 25, np.nan, 41, -1, 38, 29, 29],
    'city':  [' Pune ', 'pune', 'DELHI', 'Delhi ', 'Mumbai', 'bombay', 'Pune.', 'Pune.'],
    'spend': ['120.5', '80.0', '200.2', 'N/A', '150.0', '99000', '110.0', '110.0'],
    'date':  ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
              '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-11'],
})
raw

   id name   age    city  spend        date
0   1  Ana  30.0   Pune   120.5  2024-01-05
1   2   Bo  25.0    pune   80.0  2024-01-06
2   3   Cy   NaN   DELHI  200.2  2024-01-07
3   4   Di  41.0  Delhi     N/A  2024-01-08
4   5  Eve  -1.0  Mumbai  150.0  2024-01-09
5   6  Fin  38.0  bombay  99000  2024-01-10
6   7  Gus  29.0   Pune.  110.0  2024-01-11
7   7  Gus  29.0   Pune.  110.0  2024-01-11

In [ ]:
df = raw.copy()        # always work on a copy
df.info()              # types + non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      8 non-null      int64
 1   name    8 non-null      object
 2   age     7 non-null      float64
 3   city    8 non-null      object
 4   spend   8 non-null      object
 5   date    8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

In [ ]:
print('Missing per column:')
print(df.isna().sum())
print('\nDuplicate rows:', df.duplicated().sum())
print('\nNote: spend is type', df['spend'].dtype, "-> stored as text!")

Missing per column:
id       0
name     0
age      1
city     0
spend    0
date     0
dtype: int64

Duplicate rows: 1

Note: spend is type object -> stored as text!

In [ ]:
# 1. Duplicate row count
print("Duplicate rows:", raw.duplicated().sum())

# 2. Missing values per column
print("\nMissing values per column:")
print(raw.isna().sum())

# 3. Problems I can see:
# - Duplicate row exists (last row is a duplicate of the previous row).
# - Missing age value (NaN for Cy).
# - Invalid age value (-1 for Eve).
# - City names are inconsistent (Pune, pune, Pune., DELHI, Delhi, bombay).
# - Extra spaces and punctuation in city names.
# - Spend column is stored as text, not numeric.
# - Spend contains a non-numeric value ('N/A').
# - Possible outlier in spend column (99000).
# - Date column is stored as string and should be converted to datetime.

Duplicate rows: 1

Missing values per column:
id       0
name     0
age      1
city     0
spend    0
date     0
dtype: int64

In [ ]:
df['spend'] = pd.to_numeric(df['spend'], errors='coerce')  # 'N/A' -> NaN, text -> number
df['age']   = df['age'].replace(-1, np.nan)                # sentinel -> NaN

print('Missing after unmasking:')
print(df[['age', 'spend']].isna().sum())

Missing after unmasking:
age      2
spend    1
dtype: int64

In [ ]:
df['age']   = df['age'].fillna(df['age'].median())
df['spend'] = df['spend'].fillna(df['spend'].median())
print('Missing after imputing:', df[['age', 'spend']].isna().sum().sum())

Missing after imputing: 0

In [ ]:
import numpy as np
import pandas as pd

ex = raw.copy()

# 1. Unmask missing values

# Convert spend to numeric
# 'N/A' becomes NaN
ex['spend'] = pd.to_numeric(ex['spend'], errors='coerce')

# Convert invalid age (-1) to NaN
ex.loc[ex['age'] == -1, 'age'] = np.nan

# 2a. Dropna version
ex_drop = ex.dropna()

# 2b. Median-impute version
ex_impute = ex.copy()

ex_impute['age'] = ex_impute['age'].fillna(
    ex_impute['age'].median()
)

ex_impute['spend'] = ex_impute['spend'].fillna(
    ex_impute['spend'].median()
)

# 3. Compare row counts
print("Original rows      :", len(ex))
print("After dropna()     :", len(ex_drop))
print("After imputation   :", len(ex_impute))

print("\nRows lost by dropna():",
      len(ex) - len(ex_drop))

Original rows      : 8
After dropna()     : 5
After imputation   : 8

Rows lost by dropna(): 3

In [ ]:
print('Before:', df.shape)
df = df.drop_duplicates()
print('After :', df.shape, '-> removed the repeated Gus row')

Before: (8, 6)
After : (7, 6) -> removed the repeated Gus row

In [ ]:
df['date'] = pd.to_datetime(df['date'])
# 'city' is a category -> mark it as such (saves memory, signals intent)
df['city'] = df['city'].astype('string')
print(df.dtypes)

id                int64
name             object
age             float64
city     string[python]
spend           float64
date     datetime64[ns]
dtype: object

In [ ]:
import pandas as pd
import numpy as np

ex = raw.copy()

# 1. Fix types

# Convert spend to numeric
# 'N/A' becomes NaN
ex['spend'] = pd.to_numeric(ex['spend'], errors='coerce')

# Convert date to datetime
ex['date'] = pd.to_datetime(ex['date'])

# 2. Drop duplicate rows
ex = ex.drop_duplicates()

# 3. Print dtypes and shape
print("Data Types:\n")
print(ex.dtypes)

print("\nShape:")
print(ex.shape)

Data Types:

id                int64
name             object
age             float64
city             object
spend           float64
date     datetime64[ns]
dtype: object

Shape:
(7, 6)

In [ ]:
q1, q3 = df['spend'].quantile([0.25, 0.75])
iqr = q3 - q1
low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr
print(f'Q1={q1:.1f}  Q3={q3:.1f}  IQR={iqr:.1f}')
print(f'Normal range: {low:.1f} to {high:.1f}')

outliers = df[(df['spend'] < low) | (df['spend'] > high)]
print('\nOutlier rows:')
print(outliers[['name', 'spend']])

Q1=115.2  Q3=175.1  IQR=59.8
Normal range: 25.5 to 264.9

Outlier rows:
  name    spend
5  Fin  99000.0

In [ ]:
df['spend_capped'] = df['spend'].clip(lower=low, upper=high)
print(df[['name', 'spend', 'spend_capped']])

  name    spend  spend_capped
0  Ana    120.5       120.500
1   Bo     80.0        80.000
2   Cy    200.2       200.200
3   Di    120.5       120.500
4  Eve    150.0       150.000
5  Fin  99000.0       264.875
6  Gus    110.0       110.000

In [ ]:
# 1. Q1, Q3, IQR for 'age'
Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)

IQR = Q3 - Q1

print("Q1 :", Q1)
print("Q3 :", Q3)
print("IQR:", IQR)

# 2. Lower & Upper Bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("\nLower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

# 3. Rows outside the bounds
outliers = df[
    (df['age'] < lower_bound) |
    (df['age'] > upper_bound)
]

print("\nRows with age outliers:")
print(outliers)

Q1 : 29.25
Q3 : 34.0
IQR: 4.75

Lower Bound: 22.125
Upper Bound: 41.125

Rows with age outliers:
Empty DataFrame
Columns: [id, name, age, city, spend, date, spend_capped]
Index: []

In [ ]:
print(df['city'].value_counts())   # ' Pune ', 'pune', 'Pune.' all look different!

city
 Pune     1
pune      1
DELHI     1
Delhi     1
Mumbai    1
bombay    1
Pune.     1
Name: count, dtype: Int64

In [ ]:
s = df['city'].astype('string')
s = s.str.strip()                       # trim whitespace
s = s.str.lower()                       # unify case
s = s.str.replace('.', '', regex=False) # drop stray punctuation
s = s.replace({'bombay': 'mumbai'})     # map known variants to one label
df['city'] = s
print(df['city'].value_counts())        # now clean categories

city
pune      3
delhi     2
mumbai    2
Name: count, dtype: Int64

In [ ]:
import pandas as pd

messy = pd.Series(
    [' London ', 'london', 'LONDON', 'N.Y.', 'new york ', 'New York'],
    dtype='string'
)

# 1. strip + lower
messy = messy.str.strip().str.lower()

# 2. map 'n.y.' -> 'new york'
messy = messy.replace('n.y.', 'new york')

# 3. value_counts()
print(messy.value_counts())

london      3
new york    3
Name: count, dtype: Int64

In [ ]:
clean = df.drop(columns=['spend_capped'])
print('Final shape:', clean.shape)
print('Missing values:', int(clean.isna().sum().sum()))
print('Duplicates    :', int(clean.duplicated().sum()))
clean

Final shape: (7, 6)
Missing values: 0
Duplicates    : 0

   id name   age    city    spend       date
0   1  Ana  30.0    pune    120.5 2024-01-05
1   2   Bo  25.0    pune     80.0 2024-01-06
2   3   Cy  29.5   delhi    200.2 2024-01-07
3   4   Di  41.0   delhi    120.5 2024-01-08
4   5  Eve  29.5  mumbai    150.0 2024-01-09
5   6  Fin  38.0  mumbai  99000.0 2024-01-10
6   7  Gus  29.0    pune    110.0 2024-01-11

In [ ]:
import pandas as pd
import numpy as np

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

print("Series s1_1:")
print(s1_1)

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

print("\nNumPy Array np_array1_2:")
print(np_array1_2)

# 1.3 Convert NumPy array to Pandas DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)

print("\nDataFrame df1_3:")
print(df1_3)

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array np_array1_2:
[[62 46 33 39]
 [85 59 92 37]
 [37 98 34 86]]

DataFrame df1_3:
    A   B   C   D
0  62  46  33  39
1  85  59  92  37
2  37  98  34  86

In [ ]:
import pandas as pd
import numpy as np

print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-10', periods=100),
    'Region': np.random.choice(
        ['East', 'West', 'North', 'South'],
        size=100
    ),
    'Product': np.random.choice(
        ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        size=100
    ),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

# Introduce 5 NaN values in Sales
sales_nan_idx = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_idx, 'Sales'] = np.nan

# Introduce 3 NaN values in Quantity
qty_nan_idx = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

# Display first few rows
print(df_sales.head())

# Verify missing values
print("\nMissing Values:")
print(df_sales.isna().sum())

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01   East     Mouse  218.0      10.0
1 2023-01-02   West   Monitor  487.0       3.0
2 2023-01-03   West     Mouse  561.0       8.0
3 2023-01-04  South  Keyboard  200.0       6.0
4 2023-01-05  South  Keyboard  426.0      10.0

Missing Values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

In [ ]:
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select only 'Region' and 'Sales' columns
df3_1 = df_sales[['Region', 'Sales']]

print("\n3.1 Region and Sales:")
print(df3_1.head())

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

print("\n3.2 Rows where Product = Laptop:")
print(df3_2.head())

# 3.3 Region = East AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

print("\n3.3 East region and Sales > 500:")
print(df3_3.head())

# 3.4 Sales value for the first Monitor entry
val3_4 = df_sales.loc[
    df_sales['Product'] == 'Monitor',
    'Sales'
].iloc[0]

print("\n3.4 First Monitor Sales Value:")
print(val3_4)

--- Task 3: Indexing and Slicing in DataFrames ---

3.1 Region and Sales:
  Region  Sales
0   East  218.0
1   West  487.0
2   West  561.0
3  South  200.0
4  South  426.0

3.2 Rows where Product = Laptop:
         Date Region Product  Sales  Quantity
5  2023-01-06   West  Laptop  346.0       5.0
9  2023-01-10  North  Laptop    NaN       3.0
10 2023-01-11   East  Laptop  531.0       9.0
14 2023-01-15  North  Laptop  661.0       2.0
17 2023-01-18   East  Laptop  415.0      10.0

3.3 East region and Sales > 500:
         Date Region  Product  Sales  Quantity
10 2023-01-11   East   Laptop  531.0       9.0
18 2023-01-19   East  Monitor  844.0       2.0
25 2023-01-26   East  Monitor  761.0       6.0
30 2023-01-31   East    Mouse  956.0       3.0
33 2023-02-03   East   Laptop  660.0       6.0

3.4 First Monitor Sales Value:
487.0

In [ ]:
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isna().sum()

print("\nMissing Values Per Column:")
print(missing_counts4_1)

# 4.2 Fill missing Sales values with the mean Sales
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

print("\nMissing Sales after filling:")
print(df4_2_filled['Sales'].isna().sum())

# 4.3 Drop rows containing any missing values
df4_3_dropped = df_sales.dropna()

print("\nOriginal Shape :", df_sales.shape)
print("After dropna() :", df4_3_dropped.shape)

--- Task 4: Data Cleaning (Handling Missing Values) ---

Missing Values Per Column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

Missing Sales after filling:
0

Original Shape : (100, 5)
After dropna() : (93, 5)

In [ ]:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

print("\nTotal_Revenue column added:")
print(df_sales[['Sales', 'Quantity', 'Total_Revenue']].head())

# 5.2 Sort by Date (ascending) then Sales (descending)
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

print("\nSorted Data:")
print(df5_2_sorted.head())

# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[
    ['Sales', 'Quantity']
].sum()

print("\nSales and Quantity Sum by Region:")
print(df5_3_grouped_region)

# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = df_sales.groupby('Product')[
    'Sales'
].mean()

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

Total_Revenue column added:
   Sales  Quantity  Total_Revenue
0  218.0      10.0         2180.0
1  487.0       3.0         1461.0
2  561.0       8.0         4488.0
3  200.0       6.0         1200.0
4  426.0      10.0         4260.0

Sorted Data:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East     Mouse  218.0      10.0         2180.0
1 2023-01-02   West   Monitor  487.0       3.0         1461.0
2 2023-01-03   West     Mouse  561.0       8.0         4488.0
3 2023-01-04  South  Keyboard  200.0       6.0         1200.0
4 2023-01-05  South  Keyboard  426.0      10.0         4260.0

Sales and Quantity Sum by Region:
          Sales  Quantity
Region
East    12706.0     120.0
North   12137.0     117.0
South   10752.0     124.0
West    15612.0     154.0

Average Sales by Product:
Product
Keyboard    498.384615
Laptop      441.833333
Monitor     542.080000
Mouse       644.000000
Name: Sales, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving car.data to car.data

In [ ]:
df = pd.read_csv('car.data')

In [ ]:
df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [ ]:
df.shape

(1727, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   vhigh    1727 non-null   object
 1   vhigh.1  1727 non-null   object
 2   2        1727 non-null   object
 3   2.1      1727 non-null   object
 4   small    1727 non-null   object
 5   low      1727 non-null   object
 6   unacc    1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

In [ ]:
df.describe(include='all')

       vhigh vhigh.1     2   2.1 small   low  unacc
count   1727    1727  1727  1727  1727  1727   1727
unique     4       4     4     3     3     3      4
top     high    high     3     4   med   med  unacc
freq     432     432   432   576   576   576   1209

In [ ]:
df.isnull().sum()

vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
print('Missing per column:')
print(df.isna().sum())
print('\nDuplicate rows:', df.duplicated().sum())
print('\nNote: spend is type', df['spend'].dtype, "-> stored as text!")

Missing per column:
vhigh      0
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64

Duplicate rows: 0

KeyError: 'spend'